Sl-13687 base64 attachment processing
SalesLoft/viewpoint pull request #2
Opened 2019-09-26 15:58 UTC by Okinskyi

Base64 encoded attachments now can be handled by `send_message` method

2019-09-27 09:56 UTC, Okinskyi commented on lib/ews/message_accessors.rb
> +      msg.draft = true
recommended fix https://stackoverflow.com/questions/36873902/rails-viewpoint-send-message-attachments

2019-09-27 10:51 UTC, IhorHalanDevPro reviewed
Is it possible to add specs for the changes?

2019-09-27 11:11 UTC, Okinskyi commented
> Is it possible to add specs for the changes?

Well, actually yes, but touched files are not covered with specs and as I think it is not necessary to write them from scratch. I'll add detailed specs to Cerebro instead

2019-09-27 11:45 UTC, IhorHalanDevPro approved these changes

2019-09-30 11:39 UTC, jodyrodd requested changes
Can we add some specs around this new functionality?

2019-09-30 15:00 UTC, Okinskyi commented
> Can we add some specs around this new functionality?

Message accessor is not covered with specs

2019-09-30 15:32 UTC, jodyrodd approved these changes
We will come back and add specs to this library after the bulk of the project is complete.

2019-10-01 12:56 UTC, merged